Bottlo/Bottlo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from page.views import custom_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('account/',include('account.urls')),
    path('customadmin/', include('customadmin.urls')),
    path('store/', include('store.urls')),
    path('cart/',include('cart.urls')),
    path('order/', include('order.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = custom_404

Bottlo/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/', views.remove_cart, name='remove_cart'),
    path('del_cart/<int:product_id>/', views.del_cart, name='del_cart'),
    
    path('apply_coupon',views.apply_coupon,name="apply_coupon"),
    path('checkout/', views.checkout, name='checkout'),
    
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_wishlist/<int:product_id>/', views.add_wishlist, name='add_wishlist'),
    path('del_wishlist/<int:product_id>/', views.del_wishlist, name='del_wishlist'),
    
    
]

Bottlo/category/models.py
from django.db import models
from django.urls import reverse


class category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(max_length=255, blank=True)
    cat_image = models.ImageField(upload_to='photos/categories', blank=True)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('product_by_category',args=[self.slug])

    def __str__(self):
        return self.category_name

Bottlo/customadmin/models.py
from django.db import models
import random
import string

# Create your models here.


def generate_coupon_code():
    # Generate a random combination of letters and digits for the code
    letters_and_digits = string.ascii_letters + string.digits
    return ''.join(random.choices(letters_and_digits, k=10))

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True, default=generate_coupon_code)
    discount = models.PositiveIntegerField()
    min_amount = models.IntegerField()
    active = models.BooleanField()
    active_date = models.DateField()
    expiry_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    

Bottlo/templates/supuser/add_product.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Add Product</h2>
                
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4">
                
                <div class="card-body">
                  
                    <form action="{% url 'add_product' %}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <div>
                            <button class="btn btn-md rounded font-sm hover-up" type="submit">Save</button>
                        </div>
                    </form>
                </div>
                
            </div> <!-- card end// -->
        </div>
    </div>
</section> <!-- content-main end// -->
{% endblock %}

Bottlo/templates/supuser/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">


<!-- Mirrored from wp.alithemes.com/html/evara/evara-backend/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:32:35 GMT -->
<head>
    <meta charset="utf-8">
    <title>Bottlo</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'imgs/theme/icon.png' %}">
    <!-- Template CSS -->
    <link href="{% static 'assets/css/main.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    {% include 'supuser/sidebar.html' %}
    {% include 'supuser/header.html' %}

    {% block content%}
    <!-- content -->
    {% endblock %}

    <script src="{% static 'assets/js/vendors/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/vendors/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/vendors/select2.min.js' %}"></script>
    <script src="{% static 'assets/js/vendors/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'assets/js/vendors/jquery.fullscreen.min.js' %}"></script>
    <script src="{% static 'assets/js/vendors/chart.js' %}"></script>
    <!-- Main Script -->
    <script src="{% static 'assets/js/main.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/custom-chart.js' %}" type="text/javascript"></script>
    
</body>


<!-- Mirrored from wp.alithemes.com/html/evara/evara-backend/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:32:57 GMT -->
</html>

Bottlo/templates/supuser/category.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Categories </h2>
            <p>Add, edit or delete a category</p>
        </div>
        <div>
            <input type="text" placeholder="Search Categories" class="form-control bg-white">
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <form action="{% url 'add_category' %}" method="post"enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="id_category_name" class="form-label">Name</label>
                            <input type="text" placeholder="Type here" class="form-control" id="id_category_name" name="category_name" />
                        </div>
                        <div class="mb-4">
                            <label for="id_slug" class="form-label">Slug</label>
                            <input type="text" placeholder="Type here" class="form-control" id="id_slug" name="slug" />
                        </div>
                        <div class="mb-4">
                            <label for="id_description" class="form-label">Description</label>
                            <textarea placeholder="Type here" class="form-control" id="id_description" name="description"></textarea>
                        </div>
                        <div class="mb-4">
                            <label for="id_cat_image" class="form-label">Product Image</label>
                            <input type="file" class="form-control" id="id_cat_image" name="cat_image" />
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">Create category</button>
                        </div>
                    </form> 
                </div>
                <div class="col-md-9">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" />
                                        </div>
                                    </th>
                                    <th>ID</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for categories in category %}
                                <tr>
                                    <td class="text-center">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" />
                                        </div>
                                    </td>
                                    <td>{{categories.id}}</td>
                                    <td>{{categories.cat_image}}</td>
                                    <td>{{categories.category_name}}</td>
                                    <td>{{categories.slug}}</td>
                                    <td class="text-end">
                                        <div class="dropdown">
                                            <a href="#" data-bs-toggle="dropdown" class="btn btn-light rounded btn-sm font-sm"> <i class="material-icons md-more_horiz"></i> </a>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="{% url 'edit_category' categories.id %}">Edit info</a>
                                                <form id="deleteForm{{ categories.id }}" action="{% url 'del_category' categories.id %}" method="post" style="display: none;">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="method" value="DELETE">
                                                  </form>
                                                  
                                                  <a class="dropdown-item text-danger" href="#" onclick="event.preventDefault(); document.getElementById('deleteForm{{ categories.id }}').submit();">Delete</a>
                                                  

                                            </div>
                                        </div> <!-- dropdown //end -->
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div> <!-- .col// -->
            </div> <!-- .row // -->
        </div> <!-- card body .// -->
    </div> <!-- card .// -->
</section>
{% endblock %}

Bottlo/templates/supuser/coupon.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Coupon Management</h2>
        </div>
        
      
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-3">
                    <form action="{% url 'add_coupon' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="id_discount" class="form-label">Discount</label>
                            <input type="number" placeholder="Type here" class="form-control" id="id_discount" name="discount" />
                        </div>
                        <div class="mb-4">
                            <label for="id_min_amount" class="form-label">Minimum Amount</label>
                            <input type="number" placeholder="Type here" class="form-control" id="id_min_amount" name="min_amount" />
                        </div>
                        <div class="mb-4">
                            <label for="id_active_date" class="form-label">Active Date</label>
                            <input type="date" class="form-control" id="id_active_date" name="active_date" />
                        </div>
                        <div class="mb-4">
                            <label for="id_expiry_date" class="form-label">Expiry Date</label>
                            <input type="date" class="form-control" id="id_expiry_date" name="expiry_date" />
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">Create coupon</button>
                        </div>
                    </form> 
                </div>
                
                <div class="col-md-9">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th >Id</th>
                                    <th>Code</th>
                                    <th>Discount</th>
                                    <th>Active Date</th>
                                    <th >Expiry Date</th>
                                    <th class="text-end">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for coupon in coupon %}
                                <tr>
                                    <td >{{coupon.id}}
                                    </td>
                                    <td>{{coupon.code}}</td>
                                    <td>{{coupon.discount}}%</td>
                                    <td>{{coupon.active_date}}</td>
                                    <td>{{coupon.expiry_date}}</td>
                                    <td >
                                        {% if coupon.active%}
                                            <form action="{% url 'desable' coupon.id %}" method="post" class="d-inline">{% csrf_token %}
                                            <td><button class="btn btn-primary block-user" data-user-id=""
                                                    data-action="block">Active</button></td>
                                            </form>
                                        {% else %}
                                            <form action="{% url 'active' coupon.id %}" method="post" class="d-inline">{% csrf_token %}
                                            <td><button class="btn btn-danger block-user" data-user-id=""
                                                        data-action="unblock">Desable</button></td>
                                            </form>
                                        {% endif %}<!-- dropdown //end -->
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div> <!-- .col// -->
            </div> <!-- .row // -->
        </div> <!-- card body .// -->
    </div> <!-- card .// -->
</section>
{% endblock %}

Bottlo/templates/supuser/edit_category.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Edit Product</h2>
                
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card mb-4">
              
                
                <div class="card-body">
                  
                    <form action="{% url 'edit_category' categories.id %}" method="post"enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid">
                            <button class="btn btn-primary" type="submit">Create category</button>
                        </div>
                    </form> 
                </div>
                
            </div> <!-- card end// -->
        </div>
    </div>
</section> <!-- content-main end// -->
{% endblock %}

Bottlo/templates/supuser/edit_product.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Edit Product</h2>
                
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4">
                <h1> {{products.id}}</h1>
                
                <div class="card-body">
                  
                    <form action="{% url 'edit_product' products.id %}" method="post" enctype="multipart/form-data">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <div>
                            <button class="btn btn-md rounded font-sm hover-up" type="submit">Save</button>
                        </div>
                    </form>
                </div>
                
            </div> <!-- card end// -->
        </div>
    </div>
</section> <!-- content-main end// -->
{% endblock %}

Bottlo/templates/supuser/header.html
{% load static %}

<main class="main-wrap">
    <header class="main-header navbar">
    <div class="col-search">
         {% comment %}<form class="searchform">
            <div class="input-group">
                <input list="search_terms" type="text" class="form-control" placeholder="Search term">
                <button class="btn btn-light bg" type="button"> <i class="material-icons md-search"></i></button>
            </div>
            <datalist id="search_terms">
                <option value="Products">
                <option value="New orders">
                <option value="Apple iphone">
                <option value="Ahmed Hassan">
            </datalist>
        </form>{% endcomment %}
    </div> 
    <div class="col-nav">
        <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"> <i class="material-icons md-apps"></i> </button>
        <ul class="nav">
            
            <li class="nav-item">
                <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
            </li>
            <li class="nav-item">
                <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
            </li>
          
            <li class="dropdown nav-item">
                <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{% static 'assets/imgs/people/avatar2.jpg' %}" alt="User"></a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                    
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="{% url 'logout' %}"><i class="material-icons md-exit_to_app"></i>Logout</a>
                </div>
            </li>
        </ul>
    </div>
    </header>
   

Bottlo/templates/supuser/order_detail.html
{% extends 'supuser/base.html' %}

{% load static %}

{% block content %}
<section class="content-main">

    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Order detail</h2>
            <p>Details for Order ID: {{ order.order_number }}</p>
        </div>
    </div>
    <div class="card">
        <header class="card-header">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 mb-lg-0 mb-15">
                    <span>
                        <i class="material-icons md-calendar_today"></i> <b>{{ order.created_at }}</b>
                    </span> <br>
                    <small class="text-muted">Order ID: {{ order.order_number }}</small>
                </div>
            </div>
        </header> <!-- card-header end// -->
        <div class="card-body">
            <div class="row mb-50 mt-20 order-info-wrap">
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-person"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Customer</h6>
                            <p class="mb-1">
                                {{ order.first_name }} {{ order.last_name }} <br>
                                {{ order.email }} <br>
                                {{ order.phone_number }}
                            </p>
                        </div>
                    </article>
                </div> <!-- col// -->
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-local_shipping"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Order info</h6>
                            <p class="mb-1">
                                Shipping: <br>
                                Pay method: {{ order.payment.payment_method }} <br>
                                Status: {{ order.status }}
                            </p>
                        </div>
                    </article>
                </div> <!-- col// -->
                <div class="col-md-4">
                    <article class="icontext align-items-start">
                        <span class="icon icon-sm rounded-circle bg-primary-light">
                            <i class="text-primary material-icons md-place"></i>
                        </span>
                        <div class="text">
                            <h6 class="mb-1">Deliver to</h6>
                            <p class="mb-1">
                                City: {{ order.city }} <br>
                                {{ order.address_line_1 }}<br>
                                {{ order.address_line_2 }}
                            </p>
                        </div>
                    </article>
                </div> <!-- col// -->
            </div> <!-- row // -->
            <div class="row">
                <div class="col-lg-7">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th width="40%">Product</th>
                                    <th width="20%">Unit Price</th>
                                    <th width="20%">Quantity</th>
                                    <th width="20%" class="text-end">Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for ordr_product in ordr_products %}
                                <tr>
                                    <td>
                                        <a class="itemside" href="#">
                                            <div class="left">
                                                <img src="{{ ordr_product.product.image.url }}" width="40" height="40" class="img-xs" alt="Item">
                                            </div>
                                            <div class="info">{{ ordr_product.product.product_name }}</div>
                                        </a>
                                    </td>
                                    <td>₹{{ ordr_product.product.price }}</td>
                                    <td>{{ ordr_product.quantity }}</td>
                                    <td class="text-end">₹{{ subtotal }}</td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td colspan="4">
                                        <article class="float-end">
                                            <dl class="dlist">
                                                <dt>Subtotal:</dt>
                                                <dd>₹{{ subtotal }}</dd>
                                            </dl>
                                            <dl class="dlist">
                                                <dt>Tax:</dt>
                                                <dd>₹{{ order.tax|floatformat:2 }}</dd>
                                            </dl>
                                            <dl class="dlist">
                                                <dt>Grand total:</dt>
                                                <dd><b class="h5">₹{{ order.order_total|floatformat:2 }}</b></dd>
                                            </dl>
                                            <dl class="dlist">
                                                <dt class="text-muted">Status:</dt>
                                                <dd>
                                                    <span class="badge rounded-pill alert-success text-success">{{ order.payment.status }}</span>
                                                </dd>
                                            </dl>
                                        </article>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div> <!-- table-responsive// -->
                </div> <!-- col// -->
                <div class="col-lg-1"></div>
                <div class="col-lg-4">
                    <div class="box shadow-sm bg-light">
                        <h6 class="mb-15">Payment info</h6>
                        <p>
                            <img src={% static 'assets/imgs/card-brands/3.png' %} class="border" height="20"> {{ order.payment.payment_method }} <br>
                            payee: Grand Market LLC <br>
                            Phone:{{ user.phone_number }}
                        </p>
                    </div>
                </div> <!-- col// -->
            </div>
        </div> <!-- card-body end// -->
    </div> <!-- card end// -->
</section>
{% endblock %}

Bottlo/templates/supuser/order_list.html
{% extends 'supuser/base.html' %}

{% load static %}
{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Order List </h2>
            <p>Lorem ipsum dolor sit amet.</p>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row gx-3">
                <div class="col-lg-4 col-md-6 me-auto">
                    <input type="text" placeholder="Search..." class="form-control">
                </div>
                <div class="col-lg-2 col-6 col-md-3">
                    <form method="GET">
                        {% csrf_token %}
                        {{ form.status }}
                        <button type="submit" class="btn btn-sm font-sm btn-light rounded">Filter</button>
                    </form>
                </div>
            </div>
        </header> <!-- card-header end// -->
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Total</th>
                            <th scope="col">Status</th>
                            <th scope="col">Date</th>
                            <th scope="col" > Action </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orders %}
                        <tr>
                            <td>{{order.order_number}}</td>
                            <td><b>{{ order.first_name }} {{ order.last_name }}</b></td>
                            <td>{{order.email}}</td>
                            <td>₹{{order.order_total}}</td>
                            <td><span class="badge rounded-pill alert-warning">{{order.status}}</span></td>
                            <td>{{order.created_at}}</td>
                            <td>
                                <a href="{% url 'order_details' order.order_number %}" class="btn btn-sm font-sm rounded btn-brand">Detail</a>
                               
                                <div class="dropdown">
                                    <button class="btn btn-sm font-sm btn-light rounded" type="button" id="statusDropdown{{ order.order_number }}" data-bs-toggle="dropdown" aria-expanded="false">
                                        Change
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="statusDropdown{{ order.order_number }}">
                                        <li><a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('statusForm{{ order.order_number }}').elements['status'].value = 'New'; document.getElementById('statusForm{{ order.order_number }}').submit();">New</a></li>
                                        <li><a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('statusForm{{ order.order_number }}').elements['status'].value = 'Accepted'; document.getElementById('statusForm{{ order.order_number }}').submit();">Accepted</a></li>
                                        <li><a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('statusForm{{ order.order_number }}').elements['status'].value = 'Completed'; document.getElementById('statusForm{{ order.order_number }}').submit();">Completed</a></li>
                                        <li><a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('statusForm{{ order.order_number }}').elements['status'].value = 'Cancelled'; document.getElementById('statusForm{{ order.order_number }}').submit();">Cancelled</a></li>
                                    </ul>
                                    <form id="statusForm{{ order.order_number }}" method="POST" action="{% url 'change_status' order.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="status" value="">
                                    </form>
                                </div>
                                
                                
                            </td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div> <!-- table-responsive //end -->
        </div> <!-- card-body end// -->
    </div> <!-- card end// -->

</section>

{% endblock %}